### ISSUE TITLE
Can't query bird6 on bird2

### ISSUE THREAD

**Issue by korzq** [xddxdd/bird-lg-go#1]
## Expected behavior
ipv6 to work in looking glass with bird2

## Actual behavior
get error ` request failed:	Get http://[redacted]:8000/bird6?q=show+protocols:	EOF`
on looking glass

## Steps to reproduce the behavior
1. run bird2
2. run `docker run -d --restart unless-stopped --user 113:113 --name lgproxy --network general --ip=172.20.1.10 -v /var/run/bird/bird.ctl:/var/run/bird/bird.ctl -v /var/run/bird/bird.ctl:/var/run/bird6/bird.ctl xddxdd/bird-lgproxy-go`

## image version
xddxdd/bird-lgproxy-go   a67e1bd3f082 

## System info
BIRD 2.0.7
Linux 4.15.0-96-generic x86_64 x86_64 GNU/Linux
Docker version 19.03.8, build afacb8b7f0

Edit: looking glass can be found [here](https://lg.as206628.net)

**Comment by xddxdd** [comment]
The socket file for bird6 is `/var/run/bird/bird6.ctl` rather than `/var/run/bird6/bird.ctl`.

Alternatively, you can set both `--bird` and `--bird6` parameter to the only socket file of bird2.

**Comment by korzq** [comment]
Thanks, it worked by mapping `/var/run/bird/bird.ctl` to `/var/run/bird/bird6.ctl ` inside the container.
