### ISSUE TITLE
Include mtr in the `bird-lgproxy-go` docker image

### ISSUE THREAD

**Issue by nervous-inhuman** [xddxdd/bird-lg-go#100]
Currently, the `bird-lgproxy-go` ships with the ability to use `mtr`, however, the container image does not contain it.
Would it be possible to add `mtr` to the container, as it is currently being done with tracerotue? 

Thanks!

**Comment by xddxdd** [comment]
I just added a `xddxdd/bird-lgproxy-go:develop-mtr` docker image. Can you try it out? I will make a new release once you confirm it's working.

I'm creating a new image because adding mtr to the existing image will change the default behavior.

**Comment by xddxdd** [comment]
Thank you for testing. New version has been released. You can switch to `xddxdd/bird-lgproxy-go:latest-mtr` for the stable version once the CI build is complete.
