### ISSUE TITLE
whois.verisign-grs.com (hard coded web site)

### ISSUE THREAD

**Issue by skanda2000** [xddxdd/bird-lg-go#101]
Is this web site down for good ? I have noticed, it is hard coded for BGP map lookup(who is database) . Any backup to to Cymru.

**Comment by xddxdd** [comment]
It is not hardcoded, it can be changed with the `--whois` flag.

Also, `whois.verisign-grs.com` is working for me.

**Comment by skanda2000** [comment]
Thanks for reply. appreciated. It is not working for us in Australia. is the URL site is https://whois.verisign-grs.com ?

**Comment by xddxdd** [comment]
`whois.verisign-grs.com` doesn't provide service over HTTP(S). It is supposed to be queried with the `whois` client, e.g. `whois -h whois.verisign-grs.com google.com`

**Comment by xddxdd** [comment]
Closing since this is not a problem with `bird-lg-go` itself.
