### ISSUE TITLE
Add 'route ....' queries

### ISSUE THREAD

**Issue by sesa-me** [xddxdd/bird-lg-go#2]
Hope you don't mind me raising requests/issues ?

- Enhancement

Add the capability to do general 'route ...' queries. These are key to help understand routes that are exported or filtered to and from peers, e.g. `show route protocol XXXXXX filtered`

-Burble

**Comment by xddxdd** [comment]
Hi,
Thanks for your suggestions. I have added "show route ..." and a "show ..." queries for general status checking.
