### ISSUE TITLE
Separate UI from server in frontend

### ISSUE THREAD

**Issue by sesa-me** [xddxdd/bird-lg-go#3]
- Enhancement

Separate the UI presentation from the server logic. 
At a minimum this should be to template the HTML in a separate file rather than having it hard coded as a go string. 

Ideally, or as a longer term goal, invert the UI logic so that instead of creating the pages on the server side, do all the presentation logic on the browser client side and have the server act as a REST API. e.g. similar to dn42regsrv, using a framework like Vue

-Burble

**Comment by xddxdd** [comment]
Hi,
Thanks for your suggestions. I've split most of the HTML into a template in "frontend/template.go" file.
As for the UI logic, I don't plan to add things like React or Vue since they're kinda heavy for the purpose. But I can definitely add a REST API.

**Comment by xddxdd** [comment]
An API is added in commit https://github.com/xddxdd/bird-lg-go/commit/da2c3d9aed7cc7dbca175673f9cfb9f54316f886. The parameters are added to README.

**Comment by sesa-me** [comment]
Cool, thanks for that update. 
I think we can probably close this issue now.
