### ISSUE TITLE
Filter protocols

### ISSUE THREAD

**Issue by decode13** [xddxdd/bird-lg-go#33]
Hi,

Is there a way to filter protocol types?
We want to expose a LG to Internet, but it should show only BGP protocol.

Thanks

**Comment by xddxdd** [comment]
Right now protocol filtering is not supported, nor do I have time right now to implement it.

If you are kind enough to submit a PR, I would happily accept that.

**Comment by xddxdd** [comment]
This has been implemented in #40.
