### ISSUE TITLE
Please document Go v1.16 requirement

### ISSUE THREAD

**Issue by athompson-merlin** [xddxdd/bird-lg-go#35]
I spent a ton of time trying to figure out why I was getting module errors, and wasn't able to download the "embed" and "io/fs" modules on a brand-new EL8 linux system.  Finally figured out that this code base requires Go v1.16 at minimum, whereas RHEL/Oracle/CentOS/Alma LInux 8 all ship with Go 1.15.
A one-liner ("Note: Go v1.16 or newer is required") at the top of the section discussing running make(1) would be sufficient.

**Comment by xddxdd** [comment]
Sorry for the trouble, I thought it was there. It has been added now.
