### ISSUE TITLE
BGPMAP only shows one path

### ISSUE THREAD

**Issue by athompson-merlin** [xddxdd/bird-lg-go#38]
I'm seeing that the BGPMAP functionality only shows one path, not all paths like the original bird-lg project this tries to replace.

Example:
http://lg2.merlin.ca/route_all/lg2/8.8.8.8
vs.
http://lg2.merlin.ca/route_bgpmap/lg2/8.8.8.8

Also important is that bgpmap is not drawing the shortest path, for some reason. 

Am I doing something wrong, or is this not implemented yet?  Unfortunately, bgpmap of all routes is the feature I was looking for.  (Well, that and compatibility with a newer runtime than Python2...)

For permanence:
```http://lg2.merlin.ca/route_all/lg2/8.8.8.8

lg2: show route for 8.8.8.8 all

Table master4:
8.8.8.0/24           unreachable [umrtr2_v4 17:43:58.084 from 206.211.216.52] * (100) [AS15169i]
	Type: BGP univ
	BGP.origin: IGP
	BGP.as_path: 10965 6509 15169
	BGP.next_hop: 206.211.216.52
	BGP.local_pref: 100
	BGP.community: (6509,65030) (10965,6509) (10965,64601)
	BGP.ext_community: (rt, 6509, 100)
	BGP.large_community: (16796, 1, 10965)
                     unreachable [umrtr1_v4 17:43:28.293 from 206.211.216.51] (100) [AS15169i]
	Type: BGP univ
	BGP.origin: IGP
	BGP.as_path: 7122 7122 577 15169
	BGP.next_hop: 206.211.216.51
	BGP.local_pref: 100
	BGP.community: (7122,1) (7122,3)
	BGP.large_community: (16796, 1, 7122)
                     unreachable [uwpg_rtr1_v4 17:43:20.593 from 206.211.216.50] (100) [AS15169i]
	Type: BGP univ
	BGP.origin: IGP
	BGP.as_path: 6327 6327 6327 15169
	BGP.next_hop: 206.211.216.50
	BGP.local_pref: 100
	BGP.community: (6327,2)
	BGP.large_community: (16796, 1, 6327)
                     unreachable [umrtr2_v4 17:43:58.030 from 206.211.216.52] (100) [AS15169i]
	Type: BGP univ
	BGP.origin: IGP
	BGP.as_path: 7122 7122 577 15169
	BGP.next_hop: 206.211.216.52
	BGP.local_pref: 100
	BGP.community: (7122,1) (7122,3)
	BGP.large_community: (16796, 1, 7122)
```

and

![image](https://user-images.githubusercontent.com/56890769/131507162-eb79bd45-65a3-4303-8a6b-507ec2779213.png)

**Comment by athompson-merlin** [comment]
FWIW, yes, two of the BGP paths are identical, that's normal in my network on any device with ADD_PATH support, like BIRD.

**Comment by xddxdd** [comment]
Showing only one path is incorrect behavior, and this is because the split point "via" doesn't exist in your bird output.

This should be fixed now following the merge of #36.

**Comment by athompson-merlin** [comment]
OK, that's some impressive turn-around time!  I'll update and test.

**Comment by athompson-merlin** [comment]
That's great, thank you.  I now see this, which appears to be correct.

![image](https://user-images.githubusercontent.com/56890769/131527386-65382a72-7eb0-402d-9dd8-be21ad467e03.png)
