### ISSUE TITLE
Whois Test failling if network not available 

### ISSUE THREAD

**Issue by Tchekda** [xddxdd/bird-lg-go#46]
Hi,
While building the package in a sandbox without internet connection, I encountered this error in the tests : 
```
whois_test.go:12: Whois AS6939 failed, got dial tcp: lookup whois.arin.net on [::1]:53: read udp [::1]:40395->[::1]:53: read: connection refused
```
Is it possible to modify the test to bypass it if network is not reachable during the test phase ?

**Comment by xddxdd** [comment]
Hi,
Thanks for your report! Now tests requiring network access are skipped when it is unavailable.

**Comment by Tchekda** [comment]
Thank you so much
