### ISSUE TITLE
traceroute arguments

### ISSUE THREAD

**Issue by tristanheaven** [xddxdd/bird-lg-go#50]
I'm not sure whether this is a feature or a bug, but `proxy` currently allows `traceroute` execution to be modified by option arguments, e.g., `-n example.com`

To prevent this, you could use `--` to terminate the option arguments:

```
% traceroute -q1 -N32 -w1 -- -n example.com
-n: Name or service not known
Cannot handle "host" cmdline arg `-n' on position 1 (argc 2)
```

Thanks.

**Comment by xddxdd** [comment]
This is intended to be a feature. I don't think supporting traceroute arguments will lead to security risks.
