### ISSUE TITLE
[Feature request] Please add config file support

### ISSUE THREAD

**Issue by CoelacanthusHex** [xddxdd/bird-lg-go#52]
Now we only support passing configuration through command line parameters or environment variables, which is inconvenient to use.
For example, a common usage method is to write a systemd service to run proxy and lg. Whether it is passed through the command line or through environment variables, the node server needs to be hard-coded in the service, which is inconvenient to use scripts for batch or automated deployment.

**Comment by jlu5** [comment]
If you're using systemd, a simple option is to use [EnvironmentFile](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=), which reads in a newline-separated list of `key=value` parameters.

**Comment by xddxdd** [comment]
Sorry for responding late, for some reason I never got the notification of this issue.

Config file support has been added.
