### ISSUE TITLE
Cross-site Scripting(XSS) vulnerability

### ISSUE THREAD

**Issue by stypr** [xddxdd/bird-lg-go#57]
### Description

I think these parameters are not properly sanitized, so it is possible to trigger arbitrary JavaScript on target's browser..

https://github.com/xddxdd/bird-lg-go/blob/af5b653326936ede439380d1a88b5ed96e4e7e8c/frontend/assets/templates/page.tpl#L31-L39

### Demo

https://lg.lantian.pub/generic/buyvm+hostdare+linkin+oracle-vm1+virmach-ny1g+local/%22%3E%3Csvg/onload=alert(document.domain)%3E

**Comment by xddxdd** [comment]
Thanks for your report! This vulnerability has been fixed in the latest commit.
