### ISSUE TITLE
bgpmap: preferred-path ASNs are not red, can make it difficult to follow on-screen

### ISSUE THREAD

**Issue by athompson-merlin** [xddxdd/bird-lg-go#66]
Trivial demonstration of issue: http://lg2.merlin.ca/route_bgpmap/lg2/8.8.8.8
(Browser: MS Edge, also happens in Firefox)

Origin server is blue, per bgpmap.go:104
Lines are red, per bgpmap.go:172 & 175
Terminal node is red, per bgpmap.go:98
However, I _think_ bgpmap.go:158 is supposed to turn the ASN circle red, and it does not do so.

Ah, now I see it's a JS lib that does the layout & rendering, oh joy...
HTML sent to browser includes, e.g. `"AS13335\nUS\narin\n2010-07-14\nCLOUDFLARENET, US" -> "Target: 1.1.1.1" [color=red];` which appears correct, or at least matches the Go code.
Problem is reproducible in the https://viz.js sandbox.

Restated problem definition: To make a node red, it must be explicitly defined in the DOT DSL, and bgpmap.go does not do so.
AddEdge() by definition cannot produce a red ASN node.  It must be added (either before or after) as a standalone node with addTarget().
e.g.
```DOT
a -> b [color=red];
```
will produce a black a, a black b, and a red edge between them.  However, 
```DOT
a [color=red];
a -> b [color=red];
b [color=red];
```
will produce an all-red path including the nodes.

As far as I can tell, adding two gratuitous addTarget calls immediately before or after each addEdge calls, in any order, for the preferred route would solve the issue.  Those two helper functions appear to be atomic, so I don't think this would introduce new problems.  That's kind of a hack, but... the problem domain - and the graphs - are so tiny, I don't see any reason to implement an elegant solution of building up the DOT tree and optimizing it.  There's no downside to having duplicate object definitions in the DOT language, other than the wasted CPU time processing their redefinitions - I wrote a tool internally that readily spews thousands of duplicated objects (not deliberately, FWIW!), and it's not an issue.

**Comment by jlu5** [comment]
> Origin server is blue, per bgpmap.go:104 Lines are red, per bgpmap.go:172 & 175 Terminal node is red, per bgpmap.go:98 However, I _think_ bgpmap.go:158 is supposed to turn the ASN circle red, and it does not do so.
> 
> Ah, now I see it's a JS lib that does the layout & rendering, oh joy... HTML sent to browser includes, e.g. `"AS13335\nUS\narin\n2010-07-14\nCLOUDFLARENET, US" -> "Target: 1.1.1.1" [color=red];` which appears correct, or at least matches the Go code. Problem is reproducible in the https://viz.js sandbox.
> 

Just for the record, changing the node colour was not something I had in mind when I wrote PR #36. A definition like that indeed only sets the colour of the line. You can see in the comparison at https://github.com/xddxdd/bird-lg-go/issues/38#issuecomment-909322641 that the node borders weren't red in either the before or after output. So it's not really a bug, just slightly different design!

**Comment by athompson-merlin** [comment]
I had completely forgotten #38 !

Anyway, no, I'm not seeing any difference in the graphical output.
However, before going too far, how do I tell for sure I'm looking at output from the correct binary?  I don't see a version or build# or date anywhere, am I just missing it?
I mention this because if I have somehow not correctly built or updated the binaries, there's not much point in worrying about anything else...

**Comment by athompson-merlin** [comment]
I am testing on that site, yes.

Do you see anything obviously wrong with the way I'm building & deploying it?  Seems hard to screw up, but obviously something's wrong!

```
[root@lg2 bird-lg-go]# pwd
/root/bird-lg-go

[root@lg2 bird-lg-go]# git log -n 1
commit 9e17b116f193870470f618b307490100d69c6f83 (HEAD -> master, origin/master, origin/HEAD)
Author: Yuhui Xu <xuyh0120@outlook.com>
Date:   Wed Dec 7 16:30:19 2022 -0600
    frontend: refactor bgpmap and fix node colors (#67)
    * frontend: refactor bgpmap and fix node colors
    * frontend: alternative way to test bgpmap

[root@lg2 bird-lg-go]# make 
make -C frontend all
make[1]: Entering directory '/root/bird-lg-go/frontend'
go build -ldflags "-w -s" -o frontend
make[1]: Leaving directory '/root/bird-lg-go/frontend'
make -C proxy all
make[1]: Entering directory '/root/bird-lg-go/proxy'
go build -ldflags "-w -s" -o proxy
make[1]: Leaving directory '/root/bird-lg-go/proxy'

[root@lg2 bird-lg-go]# systemctl stop bird-lg-proxy.service bird-lg-webservice.service 

[root@lg2 bird-lg-go]# make install
install -m 755 frontend/frontend /usr/local/bin/bird-lg-go
install -m 755 proxy/proxy /usr/local/bin/bird-lgproxy-go

[root@lg2 bird-lg-go]# systemctl start bird-lg-proxy.service bird-lg-webservice.service 
```

that's taken directly from my terminal scrollback buffer just now.

**Comment by xddxdd** [comment]
Maybe check the systemd service files that they are using the correct executable?

BTW I just updated my site to the latest version.

**Comment by athompson-merlin** [comment]
Looks like I had never successfully updated the running service since I initially deployed it >1yr ago :-(.
The good news is that's fixed now.
And my instance now shows the preferred path all in red, making it easy to see.
Thank you for the quick turnaround!
