### ISSUE TITLE
Able to access bird-lg-go frontend but error

### ISSUE THREAD

**Issue by myrsk** [xddxdd/bird-lg-go#68]
Hello,

I am running both the frontend and the proxy on the same server using 2 docker containers, one is the frontend, and one is the proxy.

Upon accessing the LG, i get dial unix /var/run/bird/bird.ctl: connect: no such file or directory

but upon using shell, and going to the dir, I see it exists

root@de-nue-01:/var/run/bird# ls
bird.ctl
root@de-nue-01:/var/run/bird# cat bird.ctl 
cat: bird.ctl: No such device or address

Appreciate any pointers, thanks :)

**Comment by xddxdd** [comment]
Please check in the container if the bird.ctl file is present.

If the file is missing, please check your `volumes` options, or try mounting the parent folder instead of the file itself.

**Comment by xddxdd** [comment]
Closed for no response.

If you have an update to this situation, feel free to reopen this issue.
