### ISSUE TITLE
Incorrect split strips the subnet mask on queries

### ISSUE THREAD

**Issue by sesa-me** [xddxdd/bird-lg-go#7]
https://github.com/xddxdd/bird-lg-go/blob/26c51176e4a7bd89f9b7bc64f8f986606922dd6a/frontend/webserver.go#L41

This should be:

```golang
split := strings.SplitN(r.URL.Path[1:], "/", 3)
```

Splitting in to 4 substrings results in the subnet mask (and anything after it) being removed from the query.

Example:

https://lg.lantian.pub/route_generic/gigsgigscloud/fd42:d42:d42:80::/64

Results in:

```text
gigsgigscloud: show route fd42:d42:d42:80::
syntax error, unexpected END, expecting '/'
```

 Burble

**Comment by xddxdd** [comment]
Thank you very much!

I forgot to change this when removing bird1 support, and removing ipv4/ipv6 from the URL.
