### ISSUE TITLE
[Feature Request] Able to set listen IP + port

### ISSUE THREAD

**Issue by rapdodge** [xddxdd/bird-lg-go#71]
Right now, bird-lg-go just support listen port only... I think it would be nice if we can set the listen ip + port too? An example, the server already have an webserver, and we want to set it to port 6789, and after that the webserver is proxying it.

Another example, the server is having multiple ipv6 addresses, ::1 is used for webserver, ::2 is used for database, etc... And the bird-lg is listen on like ::123

Best regards,

**Comment by xddxdd** [comment]
Hi,

You can set `BIRDLG_LISTEN` to something like `127.0.0.1:6789`.

**Comment by rapdodge** [comment]
> Hi,
> 
> You can set `BIRDLG_LISTEN` to something like `127.0.0.1:6789`.

I thought it just was for port only... Thanks.
