### ISSUE TITLE
bgpmap options not applied

### ISSUE THREAD

**Issue by famfo** [xddxdd/bird-lg-go#72]
When running the frontend on one of our servers (running Alpine Linux), the bgpmap options are not being applied (see right screenshot or [the lg directly](https://lg.famfo.xyz)). Running the same binary (compiled for musl) locally, the options get applied (left screenshot).
![image](https://user-images.githubusercontent.com/44938471/212109576-663b49c1-46ff-44ce-a43c-653ed282416c.png)

**Comment by xddxdd** [comment]
From the output, the `bgpmapInfo` option is applied correctly.

It appears that you have set `dnsInterface` incorrectly. It should point to a service that returns AS information as a TXT record, such as `asn.cymru.com`; try `dig TXT AS1.asn.cymru.com`. Your specific DNS query seem to return an unrelated TXT record that interferes with the AS lookup process.

You can set `dnsInterface` to an empty string to disable the DNS lookup.

**Comment by famfo** [comment]
Setting the `dnsInterface` to an empty string worked. Don't know why it happened, set the same DNS server both times.
