### ISSUE TITLE
Issues when having multiple networks

### ISSUE THREAD

**Issue by dimaguy** [xddxdd/bird-lg-go#83]
I'd like to have Clearnet, dn42 and yggdrasil data available from a single looking glass instance, but it doesn't seem to work right. WHOIS fails on dn42 and traceroute fails on yggdrasil addresses(there's no whois in yggdrasil, so that doesn't concern me), is there anything I'm missing?

**Comment by jlu5** [comment]
There's an example whois.conf for dn42 at https://dn42.dev/services/Whois#using-a-whois-config

**Comment by xddxdd** [comment]
Bird-lg-go doesn't do any special handling for traceroutes, all it does is calling the system `traceroute` or `mtr` binary. Please try running `traceroute` yourself and make sure that works.

**Comment by dimaguy** [comment]
Thanks! WHOIS seems to be solved, but traceroute isn't.
I've ran traceroute in the system and it succeeds, just not in the lg
In the terminal
![image](https://github.com/xddxdd/bird-lg-go/assets/7207103/47a4ef18-c979-493f-824c-467e3b3ea84e)
In the looking glass
![image](https://github.com/xddxdd/bird-lg-go/assets/7207103/acd289e3-4690-4890-afe1-7b5dfa2e6610)

**Comment by xddxdd** [comment]
Are you running lgproxy in some sort of restricted environment, e.g. Docker container, that doesn't have IPv6 access?

**Comment by xddxdd** [comment]
Here's my guess about the yggdrasil traceroute problem:

Maybe the IPv6 address of your lgproxy container is not in yggdrasil's IP range. Since yggdrasil won't know how to route packets back to this IP, it simply rejects the packets.

Please try adding a SNAT rule with `ip6tables` to force use yggdrasil's IP:

```
ip6tables -t nat -A POSTROUTING -o yggdrasil -j MASQUERADE
```

**Comment by xddxdd** [comment]
For the whois issue, please try the latest `xddxdd/bird-lg-go:develop` image. I have added a whois client and configured frontend to use that by default.

**Comment by dimaguy** [comment]
> Here's my guess about the yggdrasil traceroute problem:
> 
> Maybe the IPv6 address of your lgproxy container is not in yggdrasil's IP range. Since yggdrasil won't know how to route packets back to this IP, it simply rejects the packets.
> 
> Please try adding a SNAT rule with `ip6tables` to force use yggdrasil's IP:
> 
> ```
> ip6tables -t nat -A POSTROUTING -o yggdrasil -j MASQUERADE
> ```

I've thought of that, but wouldn't it remove all other connectivity?
There's already a route in the kernel that moves all packets in the 0200::/7 range to the yggdrasil tun0 interface, it's just weird how the container isn't using it

**Comment by dimaguy** [comment]
> For the whois issue, please try the latest `xddxdd/bird-lg-go:develop` image. I have added a whois client and configured frontend to use that by default.

I gave a go to the whois client in that image, and it seems to disregard /etc/whois.conf files(I did bind mount the file), only using the default whois server for everything. I've tried strace on the binary and I believe it simply doesn't attempt to open any config file path to read from

**Comment by xddxdd** [comment]
Try again, I added the missing config option for using config files.

**Comment by dimaguy** [comment]
> Try again, I added the missing config option for using config files.
I can tell it uses the config file now, but for some reason it still fails.
Here's the strace of the binary that I've extracted from the container image
I've tried the same config file on the OS' whois utility and it works, so I can tell that at least the file isn't at fault
ˋˋ
execve("./whois", ["./whois", "internal.dn42"], 0xfffff1d2d698 /* 33 vars */) = 0
set_tid_address(0x434f88)               = 2568820
brk(NULL)                               = 0x12a73000
brk(0x12a75000)                         = 0x12a75000
mmap(0x12a73000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x12a73000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xffff9dc10000
rt_sigprocmask(SIG_UNBLOCK, [RT_1 RT_2], NULL, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x4007c0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x41312c}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x4007c0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x41312c}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGALRM, {sa_handler=0x4007a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x41312c}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
openat(AT_FDCWD, "/etc/whois.conf", O_RDONLY|O_LARGEFILE) = 3
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xffff9dc0f000
read(3, "\\.dn42$           whois.dn42\n\\-D"..., 1024) = 541
read(3, "", 1024)                       = 0
close(3)                                = 0
munmap(0xffff9dc0f000, 4096)            = 0
ioctl(1, TIOCGWINSZ, {ws_row=43, ws_col=164, ws_xpixel=0, ws_ypixel=0}) = 0
writev(1, [{iov_base="No whois server is known for thi"..., iov_len=49}, {iov_base="\n", iov_len=1}], 2No whois server is known for this kind of object.
) = 50
exit_group(1)                           = ?
+++ exited with 1 +++
ˋˋ

**Comment by xddxdd** [comment]
Try again, the `whois` client has a compatibility issue with Alpine's musl libc, and the ability to parse regex wasn't compiled.

**Comment by dimaguy** [comment]
It's partially working now, it gives me "exit code 2" on all results (both dn42 and clearnet) in the looking glass UI, but the extracted binary gives me the correct output

**Comment by dimaguy** [comment]
in another news, it seems that traceroute of the container only works on ipv4 addresses, because I just tried to force it on an ipv6 in the dn42 network and it couldn't connect
![image](https://github.com/xddxdd/bird-lg-go/assets/7207103/87e31e02-da89-4331-aed0-aae8bf2f1e73)
This might shed some light on that issue as well

**Comment by xddxdd** [comment]
Please try again, hopefully `whois` will be fully working this time.

For your IPv6 traceroute issue, it looks like you never enabled IPv6 networking on your Docker daemon.

**Comment by dimaguy** [comment]
Whois seems to be indeed fully working this time, thanks! Are you going to move the develop image to the latest tag, or do I keep it as-is?

Also, it does seem that docker doesn't enable ipv6 by default :/ Sorry for wasting your time with this one

**Comment by xddxdd** [comment]
I'm releasing the new version now. Thanks for your suggestion for adding a whois client!
