### ISSUE TITLE
若有部分服务器的 Proxy 暂时无法访问或者无法连接，主页或者本服务器页面会长时间陷入加载状态 。

### ISSUE THREAD

**Issue by confuseder** [xddxdd/bird-lg-go#89]
目前的后端程序需要全部的 Proxy 都返回结果之后才会返回结果，如果有部分服务器的 Proxy 无法访问就会长时间加载最后超时。可不可以修改一下这部分的逻辑。

**Comment by xddxdd** [comment]
由于现在 bird-lg-go 是在服务器端拼接 HTML 生成页面，目前无法将每个 Proxy 的结果分开返回，只能返回一个完整网页。如果要进行修改，需要重写整个前端逻辑，用 AJAX 取数据，修改量较大。

**Comment by confuseder** [comment]
> 由于现在 bird-lg-go 是在服务器端拼接 HTML 生成页面，目前无法将每个 Proxy 的结果分开返回，只能返回一个完整网页。如果要进行修改，需要重写整个前端逻辑，用 AJAX 取数据，修改量较大。

适当的缩短超时时间是不是也是一种可行的方案，至少不要最后导致请求整个超时，时间内获取多少最后就返回多少。

现在是最后直接 http error 了，其实一个请求 3 秒获取不了基本上也就是没法访问了。

**Comment by xddxdd** [comment]
请试一下 master 分支的最新版本，添加了 `--connection-time-out` 参数，用于 TCP 连接超时，默认为 5 秒。

**Comment by confuseder** [comment]
已经好了，谢谢您。
