### ISSUE TITLE
Improving the frontend

### ISSUE THREAD

**Issue by bl0way** [xddxdd/bird-lg-go#96]
Hello!

I would like to use `bird-lg-go` frontend for a quite consequent number of routers (around 200) in a lab. The good point is that the features from the frontend are working well even with this number :smiley:. But unfortunately the usability is a bit tricky as we can see on those screenshots (left and right views):
![screenshot_left](https://github.com/xddxdd/bird-lg-go/assets/79900311/a9693438-be7b-4a3c-99a6-10068b2fbc35) ![image](https://github.com/xddxdd/bird-lg-go/assets/79900311/0acdcf84-b952-4bd2-9b86-16e06882fcd8)

So, it is still working well, just the disposition of "objects" are not "scaling up" (I guess).

**Comment by LeoOMaia** [comment]
I'm having the same problem, the search button is very crushed and I can't read what I'm writing due to the number of servers I'm using

**Comment by xddxdd** [comment]
Please try the latest version on `master` branch. I have adjusted the search box size, and server buttons will now wrap into new lines if necessary.

**Comment by LeoOMaia** [comment]
I think the image has not been updated, could you check for me? @xddxdd 
![image](https://github.com/xddxdd/bird-lg-go/assets/101437950/2ff86f72-4636-4f68-a2e5-e9ad3c182612)

**Comment by bl0way** [comment]
> Please try the latest version on `master` branch. I have adjusted the search box size, and server buttons will now wrap into new lines if necessary.

Thanks, it works as expected for me! For my side this issue can be closed :smile:

**Comment by LeoOMaia** [comment]
Oh, sorry, I changed the tag to 'developed' and it worked well. To update the 'latest' tag with these changes, do you have a prediction? Because I think it's more secure for me to use the latest. Now, the update looks very good.

**Comment by xddxdd** [comment]
Thanks for your confirmation of fix, I just released a new version.
