### ISSUE TITLE
Dynamic BGP sessions show up in red

### ISSUE THREAD

**Issue by rissson** [xddxdd/bird-lg-go#97]
BGP dynamic sections (described [here](https://bird.network.cz/?get_doc&v=20&f=bird-6.html#ss6.4) under the `neighbor` option) allow bird to wait for a neighbor to connect and then creates an new dynamic protocol in bird.

That new dynamic protocol shows up properly in green, but the initial protocol always stays in `start` state and thus shows up in red:

![image](https://github.com/xddxdd/bird-lg-go/assets/18313093/8286b05e-57d9-451e-ad47-306e8ba41a8a)

Real-time example at https://lg.lama.tel

I looked a bit at the code that does the rendering, and because it bases the color on the `state` attribute, it doesn't look at the info that says "passive". What would be the best way forward to get this to not show up in red?

I'm very much willing to contribute code to the project, just asking for guidance before I write anything

**Comment by xddxdd** [comment]
In my opinion, the best way to handle this is to check the "passive" text and override the row color in this case.
