### ISSUE TITLE
Next hop issue

### ISSUE THREAD

**Issue by prajaktapatil60** [xddxdd/bird-lg-go#99]
How can we achieve resolution for the next hop/32 in BGP? We've configured some static routes, but how can we export them into BGP or redistribute them into the routing table to resolve the next hops?

**Comment by xddxdd** [comment]
The issues section is only for discussing issues about the bird-lg-go software. For usage questions related to BIRD itself, I suggest you to use BIRD's official mailing list: https://bird.network.cz/?m_list
